'use strict';

/**
 * Every word the guest page says, in every language it offers.
 *
 * The selector used to change one thing: the language the review was written
 * in. That was half a feature. A guest who cannot read English cannot read
 * "Browse for more topics" either, and a page that hands them a Thai review
 * surrounded by English chrome is telling them the review is a translation
 * rather than their own words.
 *
 * One table, on the server, for two reasons. The page's own text and the
 * errors the server sends back are read by the same person in the same moment,
 * so splitting them would translate half of what they see. And the language
 * list in config.js decides what the prompt accepts — keeping the strings
 * beside it means a language cannot be offered without the words to offer it
 * in, which the tests enforce.
 *
 * Placeholders are {braced}. There is no plural machinery beyond one/many:
 * every language here either has that distinction or has none, and a CLDR
 * plural engine for "3 more tries" would be the tail wagging the dog. The
 * languages with no plural — Thai, Chinese, Japanese, Korean — write both
 * forms the same, which is correct rather than a shortcut.
 *
 * Business words are not here. Topic labels are the business's own ("The Bar",
 * "ห้องพัก") and platform names are proper nouns; translating either would be
 * inventing words nobody wrote.
 */

const STRINGS = {
  en: {
    title: 'Leave a review',
    heading: 'Thanks for stopping by',
    lede: "Here's a review in your words. Change anything you like, then post it.",
    picker: 'What stood out?',
    browseMore: 'Browse for more topics ({n})',
    allTopics: "All topics",
    searchTopics: "Search topics",
    noMatches: "No topics match that.",
    done: "Done",
    lengthLabel: 'How long?',
    lengthAny: 'Any',
    lengthShort: 'Short',
    lengthDetailed: 'Detailed',
    reviewLabel: 'Your review',
    placeholder: "Press Regenerate to write your first review.",
    generate: 'Generate',
    generateCount: 'Generate ({used}/{max})',
    regenerate: 'Regenerate',
    regenerateCount: 'Regenerate ({used}/{max})',
    copy: 'Copy',
    copied: 'Copied',
    language: 'Language',
    proceed: 'Proceed to {place}',
    hint: 'Copies your review, then opens the listing.',
    noLink: 'No review link set yet.',
    setupOwner: 'If this is your business, finish setting it up',
    pasteCopied:
      'Your review has been copied. Paste it into the review box on {place}.',
    pasteManual:
      'Select the review and copy it, then tap "Write a review" on {place}.',
    nothingToCopy: 'Nothing to copy yet.',
    languageChanged: 'The next one will be written in that language.',
    lastTry: 'That is the last one for now. Edit it however you like.',
    triesOne: '{n} more try for now.',
    triesMany: '{n} more tries for now.',
    loadFailed: 'Could not load the page settings.',
    writerFailed: 'Could not reach the writer. Try again.',
    noKey: 'No OpenRouter key yet. Add one in Settings.',
    tooFast: 'That is a lot of reviews. Wait a moment and try again.',
    outOfTries:
      'You have used the reviews available for now. Edit the one you have — it is yours to change.',
    writerDown: "The writer is unavailable right now. Try again.",
    noteLabel: 'Anything to add?',
    notePlaceholder: 'The pool, breakfast, the view…',
    noteOffTopic: 'That note does not look like it is about your visit. Tell us what happened here and try again.',
    writerEmpty: "The writer came back empty. Try again.",
    // The welcome page (public/welcome.html).
    welcomeTitle: "Welcome",
    welcomeHeading: "Welcome to {venue}",
    welcomeLede: "Add your name and email to see everything we have put here for your stay.",
    welcomeName: "Your name",
    welcomeEmail: "Email",
    welcomeConsent: "Send me news and offers from {venue}",
    welcomeContinue: "Continue",
    welcomePrivacy: "{venue} keeps your name and email. You only get emails from them if you tick the box.",
    welcomeNeedName: "Add your name.",
    welcomeNameLong: "That name is too long.",
    welcomeNeedEmail: "Add an email address we can reach you on.",
    welcomeSlowDown: "Too many tries. Wait a minute and try again.",
    welcomeFailed: "Something went wrong. Try again.",
    welcomeLinks: "For your stay",
    welcomeNoLinks: "Nothing here yet — ask at the front desk.",
    installHeading: "Get the {venue} app",
    installButton: "Install",
    installIos: "On iPhone: tap Share, then \"Add to Home Screen\".",
    installAndroid: "On Android: tap the ⋮ menu, then \"Install app\" or \"Add to Home screen\".",
    installDone: "It is on your phone now. Open it from your home screen any time.",
    // The guest app, once signed up.
    installLede: "Open it from your home screen like any other app. No app store needed.",
    installLater: "Not now",
    appHello: "Hi, {name}",
    appReview: "How was your stay?",
    appReviewAction: "Leave a review",
    appSignedIn: "Signed in as {name}",
    appNotYou: "Not you?",
    appOffline: "You are offline. These are the links from your last visit.",
  },

  th: {
    title: 'เขียนรีวิว',
    heading: 'ขอบคุณที่มาใช้บริการ',
    lede: 'นี่คือรีวิวในคำพูดของคุณ แก้ไขได้ตามต้องการ แล้วโพสต์เลย',
    picker: 'อะไรที่ประทับใจคุณ?',
    browseMore: 'ดูหัวข้ออื่นเพิ่มเติม ({n})',
    allTopics: "หัวข้อทั้งหมด",
    searchTopics: "ค้นหาหัวข้อ",
    noMatches: "ไม่พบหัวข้อที่ตรงกับคำค้นหา",
    done: "เสร็จสิ้น",
    lengthLabel: 'ความยาวเท่าไร?',
    lengthAny: 'แบบไหนก็ได้',
    lengthShort: 'สั้น',
    lengthDetailed: 'ละเอียด',
    reviewLabel: 'รีวิวของคุณ',
    placeholder: "กด \"สร้างใหม่\" เพื่อเขียนรีวิวแรกของคุณ",
    generate: 'สร้างรีวิว',
    generateCount: 'สร้างรีวิว ({used}/{max})',
    regenerate: 'สร้างใหม่',
    regenerateCount: 'สร้างใหม่ ({used}/{max})',
    copy: 'คัดลอก',
    copied: 'คัดลอกแล้ว',
    language: 'ภาษา',
    proceed: 'ไปที่ {place}',
    hint: 'คัดลอกรีวิวของคุณ แล้วเปิดหน้าร้าน',
    noLink: 'ยังไม่ได้ตั้งลิงก์รีวิว',
    pasteCopied: 'คัดลอกรีวิวของคุณแล้ว วางลงในช่องเขียนรีวิวที่ {place}',
    setupOwner: 'หากนี่คือธุรกิจของคุณ ตั้งค่าให้เสร็จ',
    pasteManual: 'เลือกรีวิวแล้วคัดลอก จากนั้นแตะ "เขียนรีวิว" ที่ {place}',
    nothingToCopy: 'ยังไม่มีอะไรให้คัดลอก',
    languageChanged: 'รีวิวถัดไปจะเขียนเป็นภาษานั้น',
    lastTry: 'นี่เป็นอันสุดท้ายในตอนนี้ แก้ไขได้ตามต้องการ',
    triesOne: 'เหลืออีก {n} ครั้งในตอนนี้',
    triesMany: 'เหลืออีก {n} ครั้งในตอนนี้',
    loadFailed: 'โหลดการตั้งค่าของหน้านี้ไม่สำเร็จ',
    writerFailed: 'ติดต่อระบบเขียนรีวิวไม่ได้ ลองอีกครั้ง',
    noKey: 'ยังไม่ได้ตั้งคีย์ OpenRouter กรุณาเพิ่มในการตั้งค่า',
    tooFast: 'รีวิวถี่เกินไป รอสักครู่แล้วลองใหม่',
    outOfTries:
      'ใช้จำนวนรีวิวที่มีครบแล้วในตอนนี้ แก้ไขรีวิวที่มีอยู่ได้ตามต้องการ เพราะเป็นของคุณ',
    writerDown: "ระบบเขียนรีวิวไม่พร้อมใช้งานในขณะนี้ ลองอีกครั้ง",
    noteLabel: 'อยากเพิ่มอะไรไหม?',
    notePlaceholder: 'สระว่ายน้ำ อาหารเช้า วิว…',
    noteOffTopic: 'ข้อความนี้ดูไม่เกี่ยวกับการเข้าพักของคุณ ลองเล่าสิ่งที่เกิดขึ้นที่นี่อีกครั้ง',
    writerEmpty: "ระบบเขียนรีวิวไม่ได้ส่งข้อความกลับมา ลองอีกครั้ง",
    // The welcome page (public/welcome.html).
    welcomeTitle: "ยินดีต้อนรับ",
    welcomeHeading: "ยินดีต้อนรับสู่ {venue}",
    welcomeLede: "กรอกชื่อและอีเมลเพื่อดูทุกอย่างที่เราเตรียมไว้สำหรับการเข้าพักของคุณ",
    welcomeName: "ชื่อของคุณ",
    welcomeEmail: "อีเมล",
    welcomeConsent: "ส่งข่าวสารและข้อเสนอจาก {venue} ให้ฉัน",
    welcomeContinue: "ดำเนินการต่อ",
    welcomePrivacy: "{venue} จะเก็บชื่อและอีเมลของคุณไว้ คุณจะได้รับอีเมลก็ต่อเมื่อติ๊กช่องด้านบนเท่านั้น",
    welcomeNeedName: "กรุณากรอกชื่อ",
    welcomeNameLong: "ชื่อยาวเกินไป",
    welcomeNeedEmail: "กรุณากรอกอีเมลที่ติดต่อได้",
    welcomeSlowDown: "ลองหลายครั้งเกินไป กรุณารอสักครู่แล้วลองใหม่",
    welcomeFailed: "เกิดข้อผิดพลาด กรุณาลองใหม่",
    welcomeLinks: "สำหรับการเข้าพักของคุณ",
    welcomeNoLinks: "ยังไม่มีข้อมูล สอบถามได้ที่แผนกต้อนรับ",
    installHeading: "ดาวน์โหลดแอป {venue}",
    installButton: "ติดตั้ง",
    installIos: "บน iPhone: แตะ แชร์ แล้วเลือก \"เพิ่มไปยังหน้าจอโฮม\"",
    installAndroid: "บน Android: แตะเมนู ⋮ แล้วเลือก \"ติดตั้งแอป\" หรือ \"เพิ่มลงในหน้าจอหลัก\"",
    installDone: "บันทึกไว้ในโทรศัพท์แล้ว เปิดจากหน้าจอหลักได้ทุกเมื่อ",
    // The guest app, once signed up.
    installLede: "เปิดจากหน้าจอหลักได้เหมือนแอปทั่วไป ไม่ต้องโหลดจากสโตร์",
    installLater: "ไว้ทีหลัง",
    appHello: "สวัสดีคุณ {name}",
    appReview: "การเข้าพักเป็นอย่างไรบ้าง",
    appReviewAction: "เขียนรีวิว",
    appSignedIn: "เข้าสู่ระบบในชื่อ {name}",
    appNotYou: "ไม่ใช่คุณใช่ไหม",
    appOffline: "คุณออฟไลน์อยู่ นี่คือลิงก์จากครั้งล่าสุดที่เปิด",
  },

  zh: {
    title: '写评价',
    heading: '感谢您的光临',
    lede: '这是用您的语气写的评价。您可以随意修改，然后发布。',
    picker: '哪里让您印象深刻？',
    browseMore: '浏览更多主题（{n}）',
    allTopics: "全部主题",
    searchTopics: "搜索主题",
    noMatches: "没有匹配的主题。",
    done: "完成",
    lengthLabel: '写多长？',
    lengthAny: '不限',
    lengthShort: '简短',
    lengthDetailed: '详细',
    reviewLabel: '您的评价',
    placeholder: "点击「重新生成」写下您的第一条评价。",
    generate: '生成评价',
    generateCount: '生成评价（{used}/{max}）',
    regenerate: '重新生成',
    regenerateCount: '重新生成（{used}/{max}）',
    copy: '复制',
    copied: '已复制',
    language: '语言',
    proceed: '前往 {place}',
    hint: '复制评价后会打开商家页面。',
    noLink: '尚未设置评价链接。',
    pasteCopied: '已复制您的评价。请粘贴到 {place} 的评价框中。',
    setupOwner: '如果这是您的商家，请完成设置',
    pasteManual: '请选中评价并复制，然后在 {place} 点击「写评价」。',
    nothingToCopy: '还没有可复制的内容。',
    languageChanged: '下一条将用该语言书写。',
    lastTry: '这是目前的最后一条。您可以随意修改。',
    triesOne: '目前还剩 {n} 次。',
    triesMany: '目前还剩 {n} 次。',
    loadFailed: '无法加载页面设置。',
    writerFailed: '无法连接生成服务，请重试。',
    noKey: '尚未设置 OpenRouter 密钥，请在设置中添加。',
    tooFast: '操作过于频繁，请稍候再试。',
    outOfTries: '目前的次数已用完。您可以修改现有的评价，它是您的。',
    writerDown: "生成服务暂时不可用，请重试。",
    noteLabel: '还想补充什么吗？',
    notePlaceholder: '泳池、早餐、风景……',
    noteOffTopic: '这段备注看起来与您这次的体验无关。请说说在这里发生的事情，然后再试一次。',
    writerEmpty: "生成服务没有返回内容，请重试。",
    // The welcome page (public/welcome.html).
    welcomeTitle: "欢迎",
    welcomeHeading: "欢迎来到 {venue}",
    welcomeLede: "填写姓名和邮箱，即可查看我们为您的入住准备的一切。",
    welcomeName: "您的姓名",
    welcomeEmail: "邮箱",
    welcomeConsent: "向我发送 {venue} 的新闻和优惠",
    welcomeContinue: "继续",
    welcomePrivacy: "{venue} 会保存您的姓名和邮箱。只有勾选上方选项，您才会收到他们的邮件。",
    welcomeNeedName: "请填写姓名。",
    welcomeNameLong: "姓名太长。",
    welcomeNeedEmail: "请填写可以联系到您的邮箱。",
    welcomeSlowDown: "尝试次数过多，请稍等一分钟再试。",
    welcomeFailed: "出了点问题，请重试。",
    welcomeLinks: "入住须知",
    welcomeNoLinks: "暂无内容，请咨询前台。",
    installHeading: "获取 {venue} 应用",
    installButton: "安装",
    installIos: "iPhone：点击\"分享\"，然后选择\"添加到主屏幕\"。",
    installAndroid: "Android：点击 ⋮ 菜单，然后选择\"安装应用\"或\"添加到主屏幕\"。",
    installDone: "已保存到手机，随时可以从主屏幕打开。",
    // The guest app, once signed up.
    installLede: "像其他应用一样从主屏幕打开，无需前往应用商店。",
    installLater: "以后再说",
    appHello: "{name}，你好",
    appReview: "这次入住感觉如何？",
    appReviewAction: "写评价",
    appSignedIn: "当前用户：{name}",
    appNotYou: "不是你？",
    appOffline: "当前离线，以下是上次访问时的链接。",
  },

  ja: {
    title: 'レビューを書く',
    heading: 'ご利用ありがとうございました',
    lede: 'あなたの言葉で書いたレビューです。自由に編集して投稿してください。',
    picker: '印象に残ったことは?',
    browseMore: '他の項目を見る ({n})',
    allTopics: "すべての項目",
    searchTopics: "項目を検索",
    noMatches: "一致する項目がありません。",
    done: "完了",
    lengthLabel: '長さは?',
    lengthAny: 'おまかせ',
    lengthShort: '短め',
    lengthDetailed: '詳しく',
    reviewLabel: 'あなたのレビュー',
    placeholder: "「作り直す」を押して最初のレビューを作成してください。",
    generate: '作成する',
    generateCount: '作成する ({used}/{max})',
    regenerate: '作り直す',
    regenerateCount: '作り直す ({used}/{max})',
    copy: 'コピー',
    copied: 'コピーしました',
    language: '言語',
    proceed: '{place} に進む',
    hint: 'レビューをコピーして掲載ページを開きます。',
    noLink: 'レビューのリンクが未設定です。',
    pasteCopied:
      'レビューをコピーしました。{place} のクチコミ入力欄に貼り付けてください。',
    setupOwner: 'これがあなたのお店なら、設定を完了してください',
    pasteManual:
      'レビューを選択してコピーし、{place} で「クチコミを書く」を押してください。',
    nothingToCopy: 'まだコピーするものがありません。',
    languageChanged: '次回はその言語で作成します。',
    lastTry: '今回はこれで最後です。自由に編集してください。',
    triesOne: '残り {n} 回です。',
    triesMany: '残り {n} 回です。',
    loadFailed: 'ページの設定を読み込めませんでした。',
    writerFailed: '生成サービスに接続できません。もう一度お試しください。',
    noKey: 'OpenRouter のキーが未設定です。設定から追加してください。',
    tooFast: '回数が多すぎます。少し待ってからお試しください。',
    outOfTries:
      '今回分のレビューをすべて使いました。今あるものを自由に編集してください。',
    writerDown: "生成サービスは現在利用できません。もう一度お試しください。",
    noteLabel: '付け加えることはありますか？',
    notePlaceholder: 'プール、朝食、景色など…',
    noteOffTopic: 'このメモはご滞在についての内容ではないようです。ここでの出来事を書いて、もう一度お試しください。',
    writerEmpty: "生成サービスから何も返りませんでした。もう一度お試しください。",
    // The welcome page (public/welcome.html).
    welcomeTitle: "ようこそ",
    welcomeHeading: "{venue}へようこそ",
    welcomeLede: "お名前とメールアドレスを入力すると、ご滞在に役立つ情報をご覧いただけます。",
    welcomeName: "お名前",
    welcomeEmail: "メールアドレス",
    welcomeConsent: "{venue}からのお知らせや特典を受け取る",
    welcomeContinue: "続ける",
    welcomePrivacy: "{venue}がお名前とメールアドレスを保管します。メールが届くのは、上のボックスにチェックを入れた場合のみです。",
    welcomeNeedName: "お名前を入力してください。",
    welcomeNameLong: "お名前が長すぎます。",
    welcomeNeedEmail: "連絡の取れるメールアドレスを入力してください。",
    welcomeSlowDown: "試行回数が多すぎます。1分ほど待ってからもう一度お試しください。",
    welcomeFailed: "問題が発生しました。もう一度お試しください。",
    welcomeLinks: "ご滞在のご案内",
    welcomeNoLinks: "まだ何もありません。フロントでお尋ねください。",
    installHeading: "{venue} のアプリを入手",
    installButton: "インストール",
    installIos: "iPhone：共有をタップし、「ホーム画面に追加」を選びます。",
    installAndroid: "Android：⋮ メニューをタップし、「アプリをインストール」または「ホーム画面に追加」を選びます。",
    installDone: "スマートフォンに保存しました。ホーム画面からいつでも開けます。",
    // The guest app, once signed up.
    installLede: "ほかのアプリと同じようにホーム画面から開けます。アプリストアは不要です。",
    installLater: "あとで",
    appHello: "{name} さん、こんにちは",
    appReview: "ご滞在はいかがでしたか？",
    appReviewAction: "レビューを書く",
    appSignedIn: "{name} としてログイン中",
    appNotYou: "別の方ですか？",
    appOffline: "オフラインです。前回表示したリンクです。",
  },

  ko: {
    title: '리뷰 작성',
    heading: '이용해 주셔서 감사합니다',
    lede: '당신의 표현으로 쓴 리뷰입니다. 원하는 대로 수정한 뒤 게시하세요.',
    picker: '무엇이 좋았나요?',
    browseMore: '다른 주제 보기 ({n})',
    allTopics: "전체 주제",
    searchTopics: "주제 검색",
    noMatches: "일치하는 주제가 없습니다.",
    done: "완료",
    lengthLabel: '길이는요?',
    lengthAny: '상관없음',
    lengthShort: '짧게',
    lengthDetailed: '자세히',
    reviewLabel: '내 리뷰',
    placeholder: "\"다시 생성\"을 눌러 첫 리뷰를 작성하세요.",
    generate: '리뷰 생성',
    generateCount: '리뷰 생성 ({used}/{max})',
    regenerate: '다시 생성',
    regenerateCount: '다시 생성 ({used}/{max})',
    copy: '복사',
    copied: '복사됨',
    language: '언어',
    proceed: '{place}(으)로 이동',
    hint: '리뷰를 복사한 뒤 등록 페이지를 엽니다.',
    noLink: '리뷰 링크가 아직 없습니다.',
    pasteCopied: '리뷰를 복사했습니다. {place}의 리뷰 입력란에 붙여넣으세요.',
    setupOwner: '이곳이 귀하의 업체라면 설정을 완료하세요',
    pasteManual: '리뷰를 선택해 복사한 뒤 {place}에서 "리뷰 쓰기"를 누르세요.',
    nothingToCopy: '아직 복사할 내용이 없습니다.',
    languageChanged: '다음 리뷰는 해당 언어로 작성됩니다.',
    lastTry: '지금은 이것이 마지막입니다. 원하는 대로 수정하세요.',
    triesOne: '지금은 {n}번 남았습니다.',
    triesMany: '지금은 {n}번 남았습니다.',
    loadFailed: '페이지 설정을 불러오지 못했습니다.',
    writerFailed: '생성 서비스에 연결할 수 없습니다. 다시 시도해 주세요.',
    noKey: 'OpenRouter 키가 없습니다. 설정에서 추가하세요.',
    tooFast: '요청이 너무 잦습니다. 잠시 후 다시 시도하세요.',
    outOfTries:
      '지금 사용할 수 있는 횟수를 모두 썼습니다. 있는 리뷰를 자유롭게 수정하세요.',
    writerDown: "생성 서비스를 지금 사용할 수 없습니다. 다시 시도해 주세요.",
    noteLabel: '덧붙일 내용이 있나요?',
    notePlaceholder: '수영장, 조식, 전망…',
    noteOffTopic: '이 메모는 이번 방문에 대한 내용이 아닌 것 같습니다. 여기에서 있었던 일을 적어 다시 시도해 주세요.',
    writerEmpty: "생성 서비스가 빈 응답을 보냈습니다. 다시 시도해 주세요.",
    // The welcome page (public/welcome.html).
    welcomeTitle: "환영합니다",
    welcomeHeading: "{venue}에 오신 것을 환영합니다",
    welcomeLede: "이름과 이메일을 입력하면 숙박에 필요한 모든 정보를 볼 수 있습니다.",
    welcomeName: "이름",
    welcomeEmail: "이메일",
    welcomeConsent: "{venue}의 소식과 혜택 받기",
    welcomeContinue: "계속",
    welcomePrivacy: "{venue}에서 이름과 이메일을 보관합니다. 위 상자에 체크한 경우에만 이메일을 받습니다.",
    welcomeNeedName: "이름을 입력하세요.",
    welcomeNameLong: "이름이 너무 깁니다.",
    welcomeNeedEmail: "연락 가능한 이메일 주소를 입력하세요.",
    welcomeSlowDown: "시도 횟수가 너무 많습니다. 잠시 후 다시 시도하세요.",
    welcomeFailed: "문제가 발생했습니다. 다시 시도하세요.",
    welcomeLinks: "숙박 안내",
    welcomeNoLinks: "아직 내용이 없습니다. 프런트에 문의하세요.",
    installHeading: "{venue} 앱 받기",
    installButton: "설치",
    installIos: "iPhone: 공유를 누른 다음 \"홈 화면에 추가\"를 선택하세요.",
    installAndroid: "Android: ⋮ 메뉴를 누른 다음 \"앱 설치\" 또는 \"홈 화면에 추가\"를 선택하세요.",
    installDone: "휴대폰에 저장되었습니다. 홈 화면에서 언제든 열 수 있습니다.",
    // The guest app, once signed up.
    installLede: "다른 앱처럼 홈 화면에서 열 수 있어요. 앱 스토어는 필요 없습니다.",
    installLater: "나중에",
    appHello: "{name}님, 안녕하세요",
    appReview: "숙박은 어떠셨나요?",
    appReviewAction: "리뷰 남기기",
    appSignedIn: "{name}(으)로 로그인됨",
    appNotYou: "본인이 아니신가요?",
    appOffline: "오프라인 상태입니다. 지난번 방문 때의 링크입니다.",
  },

  es: {
    title: 'Escribir una reseña',
    heading: 'Gracias por tu visita',
    lede: 'Aquí tienes una reseña con tus palabras. Cámbiala como quieras y publícala.',
    picker: '¿Qué te llamó la atención?',
    browseMore: 'Ver más temas ({n})',
    allTopics: "Todos los temas",
    searchTopics: "Buscar temas",
    noMatches: "Ningún tema coincide.",
    done: "Listo",
    lengthLabel: '¿Qué extensión?',
    lengthAny: 'Cualquiera',
    lengthShort: 'Corta',
    lengthDetailed: 'Detallada',
    reviewLabel: 'Tu reseña',
    placeholder: "Pulsa \"Generar otra\" para escribir tu primera reseña.",
    generate: 'Generar',
    generateCount: 'Generar ({used}/{max})',
    regenerate: 'Generar otra',
    regenerateCount: 'Generar otra ({used}/{max})',
    copy: 'Copiar',
    copied: 'Copiado',
    language: 'Idioma',
    proceed: 'Ir a {place}',
    hint: 'Copia tu reseña y abre la ficha.',
    noLink: 'Todavía no hay enlace de reseñas.',
    pasteCopied:
      'Tu reseña se ha copiado. Pégala en el cuadro de reseñas de {place}.',
    setupOwner: 'Si este es tu negocio, termina de configurarlo',
    pasteManual:
      'Selecciona la reseña y cópiala, luego pulsa "Escribir una reseña" en {place}.',
    nothingToCopy: 'Todavía no hay nada que copiar.',
    languageChanged: 'La siguiente se escribirá en ese idioma.',
    lastTry: 'Esta es la última por ahora. Edítala como quieras.',
    triesOne: 'Queda {n} intento por ahora.',
    triesMany: 'Quedan {n} intentos por ahora.',
    loadFailed: 'No se pudo cargar la configuración de la página.',
    writerFailed: 'No se pudo conectar con el generador. Inténtalo de nuevo.',
    noKey: 'Todavía no hay clave de OpenRouter. Añade una en Ajustes.',
    tooFast: 'Son muchas reseñas seguidas. Espera un momento e inténtalo de nuevo.',
    outOfTries:
      'Has usado las reseñas disponibles por ahora. Edita la que tienes: es tuya.',
    writerDown: "El generador no está disponible ahora mismo. Inténtalo de nuevo.",
    noteLabel: '¿Algo que añadir?',
    notePlaceholder: 'La piscina, el desayuno, las vistas…',
    noteOffTopic: 'Esa nota no parece ser sobre tu visita. Cuéntanos qué pasó aquí e inténtalo de nuevo.',
    writerEmpty: "El generador no devolvió nada. Inténtalo de nuevo.",
    // The welcome page (public/welcome.html).
    welcomeTitle: "Bienvenido",
    welcomeHeading: "Bienvenido a {venue}",
    welcomeLede: "Añade tu nombre y tu correo para ver todo lo que hemos preparado para tu estancia.",
    welcomeName: "Tu nombre",
    welcomeEmail: "Correo electrónico",
    welcomeConsent: "Envíame novedades y ofertas de {venue}",
    welcomeContinue: "Continuar",
    welcomePrivacy: "{venue} guarda tu nombre y tu correo. Solo recibirás correos si marcas la casilla.",
    welcomeNeedName: "Añade tu nombre.",
    welcomeNameLong: "Ese nombre es demasiado largo.",
    welcomeNeedEmail: "Añade un correo en el que podamos contactarte.",
    welcomeSlowDown: "Demasiados intentos. Espera un minuto y vuelve a intentarlo.",
    welcomeFailed: "Algo salió mal. Inténtalo de nuevo.",
    welcomeLinks: "Para tu estancia",
    welcomeNoLinks: "Aún no hay nada aquí; pregunta en recepción.",
    installHeading: "Descarga la app de {venue}",
    installButton: "Instalar",
    installIos: "En iPhone: toca Compartir y luego \"Añadir a pantalla de inicio\".",
    installAndroid: "En Android: toca el menú ⋮ y luego \"Instalar aplicación\" o \"Añadir a pantalla de inicio\".",
    installDone: "Ya está en tu teléfono. Ábrelo desde la pantalla de inicio cuando quieras.",
    // The guest app, once signed up.
    installLede: "Ábrela desde la pantalla de inicio como cualquier otra app, sin pasar por la tienda.",
    installLater: "Ahora no",
    appHello: "Hola, {name}",
    appReview: "¿Qué tal tu estancia?",
    appReviewAction: "Deja una reseña",
    appSignedIn: "Has entrado como {name}",
    appNotYou: "¿No eres tú?",
    appOffline: "Sin conexión: estos son los enlaces de tu última visita.",
  },

  fr: {
    title: 'Laisser un avis',
    heading: 'Merci de votre visite',
    lede: 'Voici un avis dans vos mots. Modifiez ce que vous voulez, puis publiez.',
    picker: "Qu'est-ce qui vous a marqué ?",
    browseMore: 'Voir plus de thèmes ({n})',
    allTopics: "Tous les thèmes",
    searchTopics: "Rechercher un thème",
    noMatches: "Aucun thème ne correspond.",
    done: "Terminé",
    lengthLabel: 'Quelle longueur ?',
    lengthAny: 'Peu importe',
    lengthShort: 'Court',
    lengthDetailed: 'Détaillé',
    reviewLabel: 'Votre avis',
    placeholder: "Touchez « Régénérer » pour écrire votre premier avis.",
    generate: 'Générer',
    generateCount: 'Générer ({used}/{max})',
    regenerate: 'Régénérer',
    regenerateCount: 'Régénérer ({used}/{max})',
    copy: 'Copier',
    copied: 'Copié',
    language: 'Langue',
    proceed: 'Aller sur {place}',
    hint: 'Copie votre avis, puis ouvre la fiche.',
    noLink: "Aucun lien d'avis pour le moment.",
    pasteCopied:
      'Votre avis a été copié. Collez-le dans le champ d’avis sur {place}.',
    setupOwner: 'Si c’est votre établissement, terminez la configuration',
    pasteManual:
      "Sélectionnez l'avis et copiez-le, puis touchez « Rédiger un avis » sur {place}.",
    nothingToCopy: 'Rien à copier pour le moment.',
    languageChanged: 'Le prochain sera écrit dans cette langue.',
    lastTry: "C'est le dernier pour le moment. Modifiez-le comme vous voulez.",
    triesOne: 'Il reste {n} essai pour le moment.',
    triesMany: 'Il reste {n} essais pour le moment.',
    loadFailed: 'Impossible de charger les paramètres de la page.',
    writerFailed: 'Impossible de joindre le générateur. Réessayez.',
    noKey: "Aucune clé OpenRouter pour l'instant. Ajoutez-en une dans les réglages.",
    tooFast: "Cela fait beaucoup d'avis. Patientez un instant et réessayez.",
    outOfTries:
      "Vous avez utilisé les avis disponibles pour le moment. Modifiez celui que vous avez : il est à vous.",
    writerDown: "Le générateur est indisponible pour le moment. Réessayez.",
    noteLabel: 'Quelque chose à ajouter ?',
    notePlaceholder: "La piscine, le petit-déjeuner, la vue…",
    noteOffTopic: "Cette note ne semble pas concerner votre séjour. Dites-nous ce qui s'est passé ici et réessayez.",
    writerEmpty: "Le générateur n'a rien renvoyé. Réessayez.",
    // The welcome page (public/welcome.html).
    welcomeTitle: "Bienvenue",
    welcomeHeading: "Bienvenue chez {venue}",
    welcomeLede: "Indiquez votre nom et votre e-mail pour voir tout ce que nous avons préparé pour votre séjour.",
    welcomeName: "Votre nom",
    welcomeEmail: "E-mail",
    welcomeConsent: "Recevoir les nouvelles et les offres de {venue}",
    welcomeContinue: "Continuer",
    welcomePrivacy: "{venue} conserve votre nom et votre e-mail. Vous ne recevrez d'e-mails que si vous cochez la case.",
    welcomeNeedName: "Indiquez votre nom.",
    welcomeNameLong: "Ce nom est trop long.",
    welcomeNeedEmail: "Indiquez une adresse e-mail où vous joindre.",
    welcomeSlowDown: "Trop de tentatives. Patientez une minute puis réessayez.",
    welcomeFailed: "Une erreur s'est produite. Réessayez.",
    welcomeLinks: "Pour votre séjour",
    welcomeNoLinks: "Rien pour l'instant — renseignez-vous à la réception.",
    installHeading: "Téléchargez l'appli {venue}",
    installButton: "Installer",
    installIos: "Sur iPhone : touchez Partager, puis « Sur l'écran d'accueil ».",
    installAndroid: "Sur Android : touchez le menu ⋮, puis « Installer l'application » ou « Ajouter à l'écran d'accueil ».",
    installDone: "C'est sur votre téléphone. Ouvrez-la depuis l'écran d'accueil quand vous voulez.",
    // The guest app, once signed up.
    installLede: "Ouvrez-la depuis l'écran d'accueil comme n'importe quelle appli, sans passer par un store.",
    installLater: "Plus tard",
    appHello: "Bonjour {name}",
    appReview: "Comment s'est passé votre séjour ?",
    appReviewAction: "Laisser un avis",
    appSignedIn: "Connecté en tant que {name}",
    appNotYou: "Ce n'est pas vous ?",
    appOffline: "Hors ligne : voici les liens de votre dernière visite.",
  },

  de: {
    title: 'Bewertung schreiben',
    heading: 'Danke für Ihren Besuch',
    lede: 'Hier ist eine Bewertung in Ihren Worten. Ändern Sie sie beliebig und posten Sie sie.',
    picker: 'Was ist Ihnen aufgefallen?',
    browseMore: 'Weitere Themen ansehen ({n})',
    allTopics: "Alle Themen",
    searchTopics: "Themen suchen",
    noMatches: "Keine Themen gefunden.",
    done: "Fertig",
    lengthLabel: 'Wie lang?',
    lengthAny: 'Egal',
    lengthShort: 'Kurz',
    lengthDetailed: 'Ausführlich',
    reviewLabel: 'Ihre Bewertung',
    placeholder: "Tippen Sie auf „Neu erstellen\", um Ihre erste Bewertung zu schreiben.",
    generate: 'Erstellen',
    generateCount: 'Erstellen ({used}/{max})',
    regenerate: 'Neu erstellen',
    regenerateCount: 'Neu erstellen ({used}/{max})',
    copy: 'Kopieren',
    copied: 'Kopiert',
    language: 'Sprache',
    proceed: 'Weiter zu {place}',
    hint: 'Kopiert Ihre Bewertung und öffnet den Eintrag.',
    noLink: 'Noch kein Bewertungslink hinterlegt.',
    pasteCopied:
      'Ihre Bewertung wurde kopiert. Fügen Sie sie im Bewertungsfeld auf {place} ein.',
    setupOwner: 'Wenn dies Ihr Betrieb ist, schließen Sie die Einrichtung ab',
    pasteManual:
      'Markieren und kopieren Sie die Bewertung, dann tippen Sie bei {place} auf „Rezension schreiben“.',
    nothingToCopy: 'Noch nichts zum Kopieren da.',
    languageChanged: 'Die nächste wird in dieser Sprache geschrieben.',
    lastTry: 'Das war die letzte für den Moment. Ändern Sie sie beliebig.',
    triesOne: 'Noch {n} Versuch für den Moment.',
    triesMany: 'Noch {n} Versuche für den Moment.',
    loadFailed: 'Die Seiteneinstellungen konnten nicht geladen werden.',
    writerFailed: 'Der Generator ist nicht erreichbar. Bitte erneut versuchen.',
    noKey: 'Noch kein OpenRouter-Schlüssel. Fügen Sie einen in den Einstellungen hinzu.',
    tooFast: 'Das sind viele Bewertungen. Warten Sie kurz und versuchen Sie es erneut.',
    outOfTries:
      'Sie haben die vorerst verfügbaren Bewertungen aufgebraucht. Bearbeiten Sie die vorhandene — sie gehört Ihnen.',
    writerDown: "Der Generator ist gerade nicht verfügbar. Bitte erneut versuchen.",
    noteLabel: 'Noch etwas hinzuzufügen?',
    notePlaceholder: 'Der Pool, das Frühstück, die Aussicht…',
    noteOffTopic: 'Diese Notiz scheint nicht von Ihrem Besuch zu handeln. Schreiben Sie, was hier passiert ist, und versuchen Sie es erneut.',
    writerEmpty: "Der Generator hat nichts zurückgegeben. Bitte erneut versuchen.",
    // The welcome page (public/welcome.html).
    welcomeTitle: "Willkommen",
    welcomeHeading: "Willkommen im {venue}",
    welcomeLede: "Gib deinen Namen und deine E-Mail-Adresse ein, um alles zu sehen, was wir für deinen Aufenthalt vorbereitet haben.",
    welcomeName: "Dein Name",
    welcomeEmail: "E-Mail",
    welcomeConsent: "Neuigkeiten und Angebote von {venue} erhalten",
    welcomeContinue: "Weiter",
    welcomePrivacy: "{venue} speichert deinen Namen und deine E-Mail-Adresse. E-Mails bekommst du nur, wenn du das Kästchen ankreuzt.",
    welcomeNeedName: "Gib deinen Namen ein.",
    welcomeNameLong: "Der Name ist zu lang.",
    welcomeNeedEmail: "Gib eine E-Mail-Adresse an, unter der wir dich erreichen.",
    welcomeSlowDown: "Zu viele Versuche. Warte eine Minute und versuche es erneut.",
    welcomeFailed: "Etwas ist schiefgelaufen. Versuche es erneut.",
    welcomeLinks: "Für deinen Aufenthalt",
    welcomeNoLinks: "Noch nichts hier – frag an der Rezeption.",
    installHeading: "Hol dir die App von {venue}",
    installButton: "Installieren",
    installIos: "Auf dem iPhone: Tippe auf Teilen, dann auf „Zum Home-Bildschirm\".",
    installAndroid: "Auf Android: Tippe auf das Menü ⋮, dann auf „App installieren\" oder „Zum Startbildschirm hinzufügen\".",
    installDone: "Jetzt ist es auf deinem Handy. Öffne es jederzeit vom Startbildschirm.",
    // The guest app, once signed up.
    installLede: "Öffne sie wie jede andere App vom Startbildschirm, ganz ohne App Store.",
    installLater: "Später",
    appHello: "Hallo {name}",
    appReview: "Wie war dein Aufenthalt?",
    appReviewAction: "Bewertung schreiben",
    appSignedIn: "Angemeldet als {name}",
    appNotYou: "Nicht du?",
    appOffline: "Du bist offline. Das sind die Links von deinem letzten Besuch.",
  },

  it: {
    title: 'Scrivi una recensione',
    heading: 'Grazie della visita',
    lede: 'Ecco una recensione con le tue parole. Modificala come vuoi e pubblicala.',
    picker: 'Cosa ti ha colpito?',
    browseMore: 'Vedi altri temi ({n})',
    allTopics: "Tutti i temi",
    searchTopics: "Cerca temi",
    noMatches: "Nessun tema corrisponde.",
    done: "Fatto",
    lengthLabel: 'Quanto lunga?',
    lengthAny: 'Indifferente',
    lengthShort: 'Breve',
    lengthDetailed: 'Dettagliata',
    reviewLabel: 'La tua recensione',
    placeholder: "Tocca \"Rigenera\" per scrivere la tua prima recensione.",
    generate: 'Genera',
    generateCount: 'Genera ({used}/{max})',
    regenerate: 'Rigenera',
    regenerateCount: 'Rigenera ({used}/{max})',
    copy: 'Copia',
    copied: 'Copiato',
    language: 'Lingua',
    proceed: 'Vai su {place}',
    hint: 'Copia la recensione e apre la scheda.',
    noLink: 'Nessun link alle recensioni.',
    pasteCopied:
      'La tua recensione è stata copiata. Incollala nel campo recensione su {place}.',
    setupOwner: 'Se questa è la tua attività, completa la configurazione',
    pasteManual:
      'Seleziona la recensione e copiala, poi tocca "Scrivi una recensione" su {place}.',
    nothingToCopy: 'Non c’è ancora nulla da copiare.',
    languageChanged: 'La prossima sarà scritta in quella lingua.',
    lastTry: 'Per ora è l’ultima. Modificala come preferisci.',
    triesOne: 'Resta {n} tentativo per ora.',
    triesMany: 'Restano {n} tentativi per ora.',
    loadFailed: 'Impossibile caricare le impostazioni della pagina.',
    writerFailed: 'Impossibile raggiungere il generatore. Riprova.',
    noKey: 'Nessuna chiave OpenRouter. Aggiungine una nelle impostazioni.',
    tooFast: 'Sono molte recensioni. Attendi un momento e riprova.',
    outOfTries:
      'Hai usato le recensioni disponibili per ora. Modifica quella che hai: è tua.',
    writerDown: "Il generatore non è disponibile in questo momento. Riprova.",
    noteLabel: 'Qualcosa da aggiungere?',
    notePlaceholder: 'La piscina, la colazione, la vista…',
    noteOffTopic: 'Questa nota non sembra riguardare la tua visita. Raccontaci cosa è successo qui e riprova.',
    writerEmpty: "Il generatore non ha restituito nulla. Riprova.",
    // The welcome page (public/welcome.html).
    welcomeTitle: "Benvenuto",
    welcomeHeading: "Benvenuto da {venue}",
    welcomeLede: "Inserisci nome ed email per vedere tutto ciò che abbiamo preparato per il tuo soggiorno.",
    welcomeName: "Il tuo nome",
    welcomeEmail: "Email",
    welcomeConsent: "Inviami notizie e offerte da {venue}",
    welcomeContinue: "Continua",
    welcomePrivacy: "{venue} conserva il tuo nome e la tua email. Riceverai email solo se spunti la casella.",
    welcomeNeedName: "Inserisci il tuo nome.",
    welcomeNameLong: "Il nome è troppo lungo.",
    welcomeNeedEmail: "Inserisci un indirizzo email a cui contattarti.",
    welcomeSlowDown: "Troppi tentativi. Attendi un minuto e riprova.",
    welcomeFailed: "Qualcosa è andato storto. Riprova.",
    welcomeLinks: "Per il tuo soggiorno",
    welcomeNoLinks: "Ancora niente qui: chiedi alla reception.",
    installHeading: "Scarica l'app di {venue}",
    installButton: "Installa",
    installIos: "Su iPhone: tocca Condividi, poi \"Aggiungi alla schermata Home\".",
    installAndroid: "Su Android: tocca il menu ⋮, poi \"Installa app\" o \"Aggiungi a schermata Home\".",
    installDone: "Ora è sul tuo telefono. Aprilo dalla schermata Home quando vuoi.",
    // The guest app, once signed up.
    installLede: "Aprila dalla schermata Home come qualsiasi altra app, senza passare dallo store.",
    installLater: "Non ora",
    appHello: "Ciao {name}",
    appReview: "Com'è andato il soggiorno?",
    appReviewAction: "Lascia una recensione",
    appSignedIn: "Accesso come {name}",
    appNotYou: "Non sei tu?",
    appOffline: "Sei offline: questi sono i link della tua ultima visita.",
  },

  pt: {
    title: 'Escrever uma avaliação',
    heading: 'Obrigado pela sua visita',
    lede: 'Aqui está uma avaliação com as suas palavras. Altere o que quiser e publique.',
    picker: 'O que se destacou?',
    browseMore: 'Ver mais temas ({n})',
    allTopics: "Todos os temas",
    searchTopics: "Procurar temas",
    noMatches: "Nenhum tema corresponde.",
    done: "Concluído",
    lengthLabel: 'Que tamanho?',
    lengthAny: 'Tanto faz',
    lengthShort: 'Curta',
    lengthDetailed: 'Detalhada',
    reviewLabel: 'A sua avaliação',
    placeholder: "Toque em \"Gerar outra\" para escrever a sua primeira avaliação.",
    generate: 'Gerar',
    generateCount: 'Gerar ({used}/{max})',
    regenerate: 'Gerar outra',
    regenerateCount: 'Gerar outra ({used}/{max})',
    copy: 'Copiar',
    copied: 'Copiado',
    language: 'Idioma',
    proceed: 'Ir para {place}',
    hint: 'Copia a avaliação e abre a página.',
    noLink: 'Ainda sem link de avaliações.',
    pasteCopied:
      'A sua avaliação foi copiada. Cole-a na caixa de avaliação em {place}.',
    setupOwner: 'Se este é o seu negócio, conclua a configuração',
    pasteManual:
      'Selecione a avaliação e copie, depois toque em "Escrever avaliação" em {place}.',
    nothingToCopy: 'Ainda não há nada para copiar.',
    languageChanged: 'A próxima será escrita nesse idioma.',
    lastTry: 'Por agora é a última. Edite-a como quiser.',
    triesOne: 'Resta {n} tentativa por agora.',
    triesMany: 'Restam {n} tentativas por agora.',
    loadFailed: 'Não foi possível carregar as definições da página.',
    writerFailed: 'Não foi possível contactar o gerador. Tente novamente.',
    noKey: 'Ainda sem chave OpenRouter. Adicione uma nas definições.',
    tooFast: 'São muitas avaliações seguidas. Aguarde um momento e tente novamente.',
    outOfTries:
      'Usou as avaliações disponíveis por agora. Edite a que tem — é sua.',
    writerDown: "O gerador está indisponível neste momento. Tente novamente.",
    noteLabel: 'Algo a acrescentar?',
    notePlaceholder: 'A piscina, o pequeno-almoço, a vista…',
    noteOffTopic: 'Essa nota não parece ser sobre a sua visita. Conte-nos o que aconteceu aqui e tente novamente.',
    writerEmpty: "O gerador não devolveu nada. Tente novamente.",
    // The welcome page (public/welcome.html).
    welcomeTitle: "Bem-vindo",
    welcomeHeading: "Bem-vindo ao {venue}",
    welcomeLede: "Informe seu nome e e-mail para ver tudo o que preparamos para a sua estadia.",
    welcomeName: "Seu nome",
    welcomeEmail: "E-mail",
    welcomeConsent: "Quero receber novidades e ofertas de {venue}",
    welcomeContinue: "Continuar",
    welcomePrivacy: "{venue} guarda seu nome e e-mail. Você só recebe e-mails se marcar a caixa.",
    welcomeNeedName: "Informe seu nome.",
    welcomeNameLong: "Esse nome é longo demais.",
    welcomeNeedEmail: "Informe um e-mail em que possamos falar com você.",
    welcomeSlowDown: "Tentativas demais. Aguarde um minuto e tente de novo.",
    welcomeFailed: "Algo deu errado. Tente de novo.",
    welcomeLinks: "Para a sua estadia",
    welcomeNoLinks: "Nada aqui ainda — pergunte na recepção.",
    installHeading: "Baixe o app de {venue}",
    installButton: "Instalar",
    installIos: "No iPhone: toque em Compartilhar e depois em \"Adicionar à Tela de Início\".",
    installAndroid: "No Android: toque no menu ⋮ e depois em \"Instalar app\" ou \"Adicionar à tela inicial\".",
    installDone: "Já está no seu celular. Abra pela tela inicial quando quiser.",
    // The guest app, once signed up.
    installLede: "Abra pela tela inicial como qualquer outro app, sem precisar da loja.",
    installLater: "Agora não",
    appHello: "Olá, {name}",
    appReview: "Como foi a sua estadia?",
    appReviewAction: "Deixe uma avaliação",
    appSignedIn: "Conectado como {name}",
    appNotYou: "Não é você?",
    appOffline: "Você está offline: estes são os links da sua última visita.",
  },

  nl: {
    title: 'Een review schrijven',
    heading: 'Bedankt voor je bezoek',
    lede: 'Dit is een review in jouw woorden. Pas aan wat je wilt en plaats hem.',
    picker: 'Wat viel je op?',
    browseMore: 'Meer onderwerpen bekijken ({n})',
    allTopics: "Alle onderwerpen",
    searchTopics: "Onderwerpen zoeken",
    noMatches: "Geen onderwerpen gevonden.",
    done: "Klaar",
    lengthLabel: 'Hoe lang?',
    lengthAny: 'Maakt niet uit',
    lengthShort: 'Kort',
    lengthDetailed: 'Uitgebreid',
    reviewLabel: 'Jouw review',
    placeholder: "Tik op \"Opnieuw\" om je eerste review te schrijven.",
    generate: 'Genereren',
    generateCount: 'Genereren ({used}/{max})',
    regenerate: 'Opnieuw',
    regenerateCount: 'Opnieuw ({used}/{max})',
    copy: 'Kopiëren',
    copied: 'Gekopieerd',
    language: 'Taal',
    proceed: 'Naar {place}',
    hint: 'Kopieert je review en opent de pagina.',
    noLink: 'Nog geen reviewlink ingesteld.',
    pasteCopied:
      'Je review is gekopieerd. Plak hem in het reviewveld op {place}.',
    setupOwner: 'Als dit jouw bedrijf is, maak de installatie af',
    pasteManual:
      'Selecteer de review en kopieer hem, tik dan bij {place} op "Een review schrijven".',
    nothingToCopy: 'Nog niets om te kopiëren.',
    languageChanged: 'De volgende wordt in die taal geschreven.',
    lastTry: 'Dit is voorlopig de laatste. Pas hem aan zoals je wilt.',
    triesOne: 'Nog {n} poging voorlopig.',
    triesMany: 'Nog {n} pogingen voorlopig.',
    loadFailed: 'Kon de pagina-instellingen niet laden.',
    writerFailed: 'Kan de generator niet bereiken. Probeer het opnieuw.',
    noKey: 'Nog geen OpenRouter-sleutel. Voeg er een toe in de instellingen.',
    tooFast: 'Dat zijn veel reviews. Wacht even en probeer het opnieuw.',
    outOfTries:
      'Je hebt de beschikbare reviews voorlopig gebruikt. Pas de review die je hebt gerust aan — hij is van jou.',
    writerDown: "De generator is nu niet beschikbaar. Probeer het opnieuw.",
    noteLabel: 'Nog iets toe te voegen?',
    notePlaceholder: 'Het zwembad, het ontbijt, het uitzicht…',
    noteOffTopic: 'Deze notitie lijkt niet over je bezoek te gaan. Vertel wat hier gebeurde en probeer het opnieuw.',
    writerEmpty: "De generator gaf niets terug. Probeer het opnieuw.",
    // The welcome page (public/welcome.html).
    welcomeTitle: "Welkom",
    welcomeHeading: "Welkom bij {venue}",
    welcomeLede: "Vul je naam en e-mailadres in om alles te zien wat we voor je verblijf klaar hebben gezet.",
    welcomeName: "Je naam",
    welcomeEmail: "E-mailadres",
    welcomeConsent: "Stuur me nieuws en aanbiedingen van {venue}",
    welcomeContinue: "Doorgaan",
    welcomePrivacy: "{venue} bewaart je naam en e-mailadres. Je krijgt alleen e-mail als je het vakje aanvinkt.",
    welcomeNeedName: "Vul je naam in.",
    welcomeNameLong: "Die naam is te lang.",
    welcomeNeedEmail: "Vul een e-mailadres in waarop we je kunnen bereiken.",
    welcomeSlowDown: "Te veel pogingen. Wacht een minuut en probeer het opnieuw.",
    welcomeFailed: "Er ging iets mis. Probeer het opnieuw.",
    welcomeLinks: "Voor je verblijf",
    welcomeNoLinks: "Nog niets hier — vraag het bij de receptie.",
    installHeading: "Download de app van {venue}",
    installButton: "Installeren",
    installIos: "Op iPhone: tik op Deel en dan op \"Zet op beginscherm\".",
    installAndroid: "Op Android: tik op het menu ⋮ en dan op \"App installeren\" of \"Toevoegen aan startscherm\".",
    installDone: "Het staat nu op je telefoon. Open het wanneer je wilt vanaf je beginscherm.",
    // The guest app, once signed up.
    installLede: "Open hem vanaf je beginscherm zoals elke andere app, zonder app store.",
    installLater: "Niet nu",
    appHello: "Hoi {name}",
    appReview: "Hoe was je verblijf?",
    appReviewAction: "Laat een review achter",
    appSignedIn: "Ingelogd als {name}",
    appNotYou: "Niet jij?",
    appOffline: "Je bent offline. Dit zijn de links van je vorige bezoek.",
  },
};

const FALLBACK = 'en';

/** Every key English has. Another language missing one is a bug, not a gap. */
const KEYS = Object.keys(STRINGS[FALLBACK]);

/**
 * One string, filled in.
 *
 * Falls back to English per key rather than per language: a language added with
 * two keys shows those two and English for the rest, which beats showing
 * English for all of it. An unknown key returns its own name — visible in
 * testing, harmless in front of a guest, and never blank.
 *
 * @param {string} lang - a language code from config.js's LANGUAGES
 * @param {string} key
 * @param {Record<string, string|number>} [vars] - fills {braced} placeholders
 */
function t(lang, key, vars = {}) {
  const table = STRINGS[lang] || STRINGS[FALLBACK];
  const raw = table[key] ?? STRINGS[FALLBACK][key] ?? key;
  return raw.replace(/\{(\w+)\}/g, (whole, name) =>
    Object.prototype.hasOwnProperty.call(vars, name) ? String(vars[name]) : whole
  );
}

/**
 * The best language for a guest we have not heard from yet.
 *
 * For the errors that happen before the page has a selector — an address
 * belonging to no business, say. Matched on the base tag, so zh-CN, zh-TW and
 * zh are one offer here, and q-values are ignored: a header in preference order
 * is close enough for one sentence.
 *
 * @param {string} header - the raw Accept-Language header
 * @param {string[]} [offered] - codes the page actually has
 */
function fromHeader(header, offered = Object.keys(STRINGS)) {
  const known = new Set(offered);
  for (const part of String(header || '').split(',')) {
    const base = part.split(';')[0].trim().toLowerCase().split('-')[0];
    if (known.has(base)) return base;
  }
  return FALLBACK;
}

/**
 * The whole table as a script the page can load.
 *
 * A script rather than JSON so it costs no fetch of its own, and every language
 * at once because the selector has to switch the page instantly — a table of
 * short strings gzips to a few kilobytes, which is cheaper than a round trip.
 *
 * Built once at boot: it cannot change without a deploy, so rebuilding it per
 * request would be work done on every guest's first paint for nothing.
 */
const SCRIPT = `window.RS_STRINGS=${JSON.stringify(STRINGS)};`;

module.exports = { STRINGS, KEYS, FALLBACK, t, fromHeader, SCRIPT };
